# Generated by Django 4.1.1 on 2022-09-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GunsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quality', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
